name: Run tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Actions checkout
        uses: actions/checkout@v3
        with:
          repository: MaksymHolovatyiDev/profiles-management-backend
          ref: master
          path: backend
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Docker Image
        working-directory: ./backend
        run: docker run -d -p 8080:8080 backend/image:1.0
      - name: Wait
        run: sleep 100
      - name: Heath check
        run: curl http://localhost:8080/api/HealthCheck
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run E2Etest
        env:
          REACT_APP_BACKEND_URL: ${{ vars.REACT_APP_BACKEND_URL }}
