name: Run tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Actions checkout
        uses: actions/checkout@v3
        with:
          repository: MaksymHolovatyiDev/profiles-management
          ref: main
          path: frontend
      - name: Actions checkout backend
        uses: actions/checkout@v3
        with:
          repository: MaksymHolovatyiDev/profiles-management-backend
          ref: master
          path: backend
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Env
        working-directory: ./backend
        run: touch .env
          echo KEY=${{ vars.KEY }}>> .env
        env:
          KEY: ${{ vars.KEY }}
          PORT: ${{ vars.PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_TEST: ${{ secrets.DB_TEST }}
      - name: Docker Image
        working-directory: ./backend
        run: |
          docker build -t backend/image:1.0 .
          docker run -d -p 8080:8080 backend/image:1.0
        env:
          KEY: ${{ vars.KEY }}
          PORT: ${{ vars.PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_TEST: ${{ secrets.DB_TEST }}
      - name: Wait
        run: sleep 20
      - name: cat
        working-directory: ./backend
        run: cat .env
      - name: Heath check
        working-directory: ./frontend
        run: curl http://localhost:8080/api/HealthCheck
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: ./frontend
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: ./frontend
        run: npm run E2Etest
        env:
          REACT_APP_BACKEND_URL: ${{ vars.REACT_APP_BACKEND_URL }}
